### ISSUE TITLE
On death cleanup would be nice

### ISSUE THREAD

**Issue by kaithar** [dreamcat4/docker-images#14] opened 2016-01-03 17:01 UTC
I was rather hoping that this container would clean up after itself, and it looks like it's supposed to be but isn't succeeding.  Here's the relevant section of logs, I've wrapped it in code block to stop markdown eating it.

```
++ docker events --since=1451839044 --filter=event=start --filter=event=die
++ echo event_line=2016-01-03T16:38:42.000000000Z fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e: '(from' 'kaithar/sqls:latest)' die
event_line=2016-01-03T16:38:42.000000000Z fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e: (from kaithar/sqls:latest) die
+++ echo -e ' 2016-01-03T16:38:42.000000000Z fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e: (from kaithar/sqls:latest) die'
+++ grep -v 'from dreamcat4/pipework'
+++ tr -s ' '
++ event_line_sanitized=' 2016-01-03T16:38:42.000000000Z fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e: (from kaithar/sqls:latest) die'
+++ echo -e ' 2016-01-03T16:38:42.000000000Z fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e: (from kaithar/sqls:latest) die'
+++ cut -d ' ' -f3
++ container_id=fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e:
+++ echo -e ' 2016-01-03T16:38:42.000000000Z fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e: (from kaithar/sqls:latest) die'
+++ cut -d ' ' -f6
++ event=die
++ '[' fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e: ']'
++ _process_container fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e die
+++ echo fb439faea533ad66bc94284cba8f147b81a8c4839147607ab047d6260336986e
+++ cut -c1-12
++ c12id=fb439faea533
++ event=die
+++ env
+++ grep -e '.*pipework.*'
+++ cut -d= -f1
++ unset pipework_cmd
+++ docker inspect --format '{{range $index, $val := .Config.Env }}{{printf "%s\"\n" $val}}{{end}}' fb439faea533
+++ grep -e 'pipework_cmd.*=\|^pipework_key=\|pipework_host_route.*='
+++ sed -e 's/^/export "/g'
++ _pipework_vars='export "pipework_cmd=br.external -i eth1 @CONTAINER_NAME@ <container ip>/27@<container" gw>'
++ '[' 'export "pipework_cmd=br.external -i eth1 @CONTAINER_NAME@ <container ip>/27@<container"' '] gw>'
+++ echo -e 'export "pipework_cmd=br.external -i eth1 @CONTAINER_NAME@ <container ip>/27@<container" gw>'
+++ grep -o -e '@CONTAINER_NAME@\|@CONTAINER_ID@\|@HOSTNAME@\|@INSTANCE@'
+++ uniq
+++ sort
++ _macros=@CONTAINER_NAME@
++ '[' @CONTAINER_NAME@ ']'
++ _expand_macros
++ for _macro in '$_macros'
++ case $_macro in
+++ docker inspect -f '{{.Name}}' fb439faea533
++ name=/sqls
+++ echo 'export "pipework_cmd=br.external -i eth1 @CONTAINER_NAME@ <container ip>/27@<container" gw>'
+++ sed -e 's|@CONTAINER_NAME@|sqls|g'
++ _pipework_vars='export "pipework_cmd=br.external -i eth1 sqls <container ip>/27@<container" gw>'
++ eval export '"pipework_cmd=br.external' -i eth1 sqls '<container ip>/27@<container" gw>'
+++ export 'pipework_cmd=br.external -i eth1 sqls <container ip>/27@<container gw>'
+++ pipework_cmd='br.external -i eth1 sqls <container ip>/27@<container gw>'
++ '[' '' ']'
+++ env
+++ grep -o -e '[^=]*pipework_cmd[^=]*'
+++ sort
++ _pipework_cmds=pipework_cmd
++ '[' pipework_cmd ']'
++ '[' die = die ']'
++ cleanup_wait=0
++ '[' '' ']'
++ '[' '' ']'
++ sleep 0
++ return 0
++ true
```

(br.external is an ovs bridge, just in case that's relevant)

Any ideas?  Need further info?

**Comment by dreamcat4** [comment] 2016-01-03 17:41
Without knowing what your problem is, the output you have shown me seem to look fairly normal.

We can't improve by adding a process supervisor inside it (such as s6), because by it's nature it requires sharing with the host PID namespace. Meaning it has to manually cleanup itself by keeping track of the PIDs of all the process it launches. There is a `_cleanup()` function near the top of the entrypoint script which is responsible for doing that.

As far as I remember, there weren't any cleanup issues. But I usually run in `batch,daemon` mode. So in that mode we issue `docker stop` to stop it. Else it keeps running by itself.

Perhaps you can also show me your orchestratoin yaml config or docker run comand?

**Comment by kaithar** [comment] 2016-01-05 05:43
I don't mean cleaning up the container processes, I mean cleaning up the connections when another container dies.

**Comment by dreamcat4** [comment] 2016-01-05 09:28
Ah ok. All that aspect of things is handled by jerome's pipework script itself. So I don't try to get involved with that in any way.

[EDIT] but you still have not stated clearly enough what your issue / problem actually is.

**Comment by kaithar** [comment] 2016-01-05 12:59
My problem is that this container is handling the setup call to pipework wonderfully, but there isn't anything happening to clean up the connections on shutdown.  The event processing script isn't actually calling out to anything when it receives a die event.  As a consequence, I now have a couple dozen lingering interfaces on the system.

I don't think jerome's script can actually handle the tear down by itself, since the container no longer exists, I'd guess that the best option would be for your code to maybe track it, though that might not hold well across restarts of the container.
Might be best to just concocting a generic clean up script to find and remove dangling interfaces, though I'm not 100% sure on how best to identify such interfaces to clean up.

**Comment by dreamcat4** [comment] 2016-01-05 15:09
Interesting... ok well from what I understand:

If you are talking about network interfaces which are created by jerome's pipework script, then they are entirely the responsibility of jerome's pipework script. Which may/may not spawn off a seperate process (which is in the host's PID namespace). I don't monitor those as architecturally any issue there would be best addressed by supplying a patch to jerome's pipework script. So that all users can benefit from such improvement (if any). Or else pipework might do cleanup the next time it's run. Either way those bit are not my container's responsibility.

But if you are talking about the `host_routes` feature: Then yes - they are created by my container. And we intentionally _do not tear down those network bridges_. The reason is that they take time to check if absent (no route). Therefore it is more performant (on container restart) to leave them in place for the next container restart. It avoids repeating a whole bunch of stuff which we did the first time around.

Those network bridges are made 1x per unique container IP address. And they are tied to that destination IP. So if your container is getting a different IP every restart - the yes sure there would be many un-needed bridges being left behind. The recommended solution for that situation is to make sure your container gets the same IP every time it is restarted. Like Static DHCP lease for example. Of course you have said you are using OVS which is different than me. Sorry I don't test anyting with OVS.

If the problem really bothers you a lot, then those bridges my script creates can be turn off by switching off the `host_route` feature entirely. The my pipework container don't create such network bridges. And that will leave you still with exactly the same functionality of jerome's official pipework script. Simple without the "host routes" enhancement added to it.

Else if are more motivated to go into that code and make a patch to improve the current `host_routes` feature with a new option to destroy those host-route bridges on container exit - the sure that's another kind of possibility. Just assuming that is actually what you are referring to here. I honestly am not certain yet. But if so - then it would have to be selectable on/off feature. As not everyone really wants it to work like that.

But let's assume none of us can have the time for that, and you still want / need the `host_routes` feature:

Can clear those network bridges by restarting your computer. Or delete them manually. And / or don't create many temporary / transient containers? Which may be other possible work-around solutions if / or can't find time to address the matter properly.

_Yet again didn't post the requested config. But in addition to that - what about these lingering network interfaces you are talking about? And the routing table. Can you please copy-paste from your machine that too? It would make a bit easier for others to understand here. Not just for me, but also for other users who may get the same issue / questions._

**Comment by kaithar** [comment] 2016-01-06 16:30
Yes, sorry, I've not had enough time at suitable times to get around to grabbing you that info til now.
Not sure exactly what you're after but here...

Pipework container config

```
        "Env": [
            "run_mode=batch,daemon",
            "host_routes=true",
            "debug=true",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "_clean=rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*",
            "_apt_clean=eval apt-get clean \u0026\u0026 rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*"
        ],
```

It hasn't actually added anything to the host routing table that I can see, I've just got the default stuff I setup and which docker setup.

Actual network setup is
`trunked network switch port` -> `linux vlan interface` -> `ovs bridge` -> `container`

3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
148: eno2.ext.252@eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ovs-system state UP mode DEFAULT group default 
179: br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 

```
        "Env": [
            "pipework_cmd=br.external -i eth1 @CONTAINER_NAME@ <external ip>/27@<gateway>"
        ],
```

The problem is that I currently have 4 running containers: your pipework container and 3 that have pipework env instructions.  They are IDs fb439faea533, 0b4316592528 and 41377d282a88.
My list of interfaces looks like this (I've filtered out a bunch of noise to make it sane):

```
# ip link list| egrep -v '(\s+link/|eno)'| sort -n
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
12: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
31: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
179: br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
209: .1p41377d282a88@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
232: veth7212092: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default 
248: .1p628a18cbfdb9@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
258: .1pafde2815d671@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
265: .1pf353b29815bb@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
278: .1pc74550de5008@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
298: .1p7f1023c07a72@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
306: .1pd5181e1251fe@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
312: .1pcb6b979281ac@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
318: .1p42a6de3a5337@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
336: .1pb573868f1086@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
348: .1pc0ca7e67b196@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
354: .1p7eb3f0eae070@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
360: .1pae6b92876384@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
378: .1pb74f2e2b52c5@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
386: .1pff78fab3eed3@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
401: .1pb768c83cd4f9@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
431: .1p163268bc519a@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
437: .1p4ae34eff1011@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
453: .1pd75e41ead76a@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
459: .1p0b4316592528@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
467: veth5e8da9a: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default 
477: .1pc3cf628dc241@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
488: .1pfb439faea533@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
505: veth3973b6e: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default 
```

You can see the 3 veth's that docker has created for eth0, aaaaand I can see the interfaces in there for eth1 on the live boxes... but the rest are left over from containers that have since been deleted.
Ideally I want a way to automatically clean up all those dangling `.1p` interfaces, since right now it's going to just keep growing until manually culled or ovs is restarted.
Restarting isn't ideal for systems that are running live containers, obviously, and while I'd prefer the containers to be longer lived a container rebuild cycle is somewhat unavoidable with how I'm iterating setting up the services running in them.

Let me know if there's more configs I should have posted, I think I got the relevant info this time but I could easily have overlooked something :)

**Comment by dreamcat4** [comment] 2016-01-06 18:05
Hi again @kaithar. Can you possibly also try to run the following cmds and paste output? There wasn't quite enough info there.

```
route
ip addr list
ip route
```

Many thanks.

**Comment by kaithar** [comment] 2016-01-06 22:45
Um, neither of those are going to be of any use to you...

I already said that the route list only containers the host's network config plus docker's `172.17.0.0/16 dev docker0`
The `ip addr list` is mostly v6 link local addresses and mac info, the only ones with v4 addresses are docker0, eno1 (the host's dedicated nic), and loopback... the interfaces I want to kill off are all some variation on the form

```
488: .1pfb439faea533@br.external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether a2:39:9d:54:25:3d brd ff:ff:ff:ff:ff:ff
    inet6 2a02:<stuff>/64 scope global mngtmpaddr dynamic 
       valid_lft 2591976sec preferred_lft 604776sec
    inet6 fe80::a039:9dff:fe54:253d/64 scope link 
       valid_lft forever preferred_lft forever
    inet6 fe80::ffff:ffff:ffff:fff3/64 scope link tentative dadfailed 
       valid_lft forever preferred_lft forever
```

**Comment by dreamcat4** [comment] 2016-01-06 23:52
OK @kaithar

The simplest test for you to perform would be to remove the environemnt variable `host_routes=true` entirely from your config. (not set it to any string value, but remove it entirely from the variable being set whatsoever). Then restart everything (including your computer etc). Without that feature enabled. To see if your issue continues to happen or not. If it still happening then we can eliminate and move forwards. But otherwise then your problem should be easily solved by disabling that.

All I can really say for sure from what you posted so far:

The indent seems to suggest OVS itself is also involved with creating these extra interfaces. If that is true, then it could be possible that your specific problem / issue may alternatively be solvable with a more sophisticated or/ tweaked OVS configuration. However OVS is such a complex networking tool.

One other thing that kindda shows is that you are linking your containers to an external bridge. So if that isn't already linked to the host in your routing table (i.e. on entirely different subnet such as `<external ip>/27@<gateway>`). Then perhaps the `host_routes` feature may be trying but failing to setup any successful bridges (even the first time around). That would offer an alternative explanation of why this problem keeps happening to you. But anyhow that is still solved by #1 solution: remove `host_routes=true` line entirely from your pipework container's config and try restart everything.

Sorry but as you didn't supply the request infos I can't really be sure of that. But you could direct-email me your full pipework logs, plus those missing infos if you wish later on. It's entirely up to you / your prerogative.

Until then it is still also remain an open question the other possibiliy of being due to pipework script itself. If yes then I could have recommended you to move this discussion over onto jerome's official pipework issue tracker in relation to OVS bridges feature. Where other experts can help further. But sorry from the infos provided it's simply not enough to confirm that yet.

So please keep in mind my #1 suggestion ^^ (turn off host routes and see). Whenever the next time you have good enough reasons to reboot / restart everything. I will leave this issue open here until then. Many thanks.

**Comment by dreamcat4** [comment] 2016-02-03 20:06
OK I'm resurrecting this issue. As it seems won't go away.

There is a similar issue on my local machine: With 17 containers running, there were about 18-19 network bridges created by the `host_routes` feature. Restarting the pipework container then created another set of bridges.

So it appears that is the problem (something in host routes feature). Therefore the previous ^^ recommendation to turn of the `host_routes` feature still stands for time being. Remain open to suggestions.

To try something else different I also disabled the `ipv6` actually in the `entrypoint.sh` code, as there is no public configuration option. Which just turns off the IPV6 part of the code. (just removing `inet6` keyword here):

https://github.com/dreamcat4/docker-images/blob/master/pipework/entrypoint.sh#L194

So my current task is to either confirm or eliminate all the IPV6 part of code as being involved (or not involved). As potentially that is quite a large block of lines, which for most of us can be switched off by default without adversely affecting anything. Don't have enough time to go through more thoroughly every single line of code (as it's quite complex).

It will take a while longer (perhaps few more days) to discover if the problem comes back again. Can't be sure yet as this issue doesn't appear straight away. To begin with, everything looks normal. Needs further testing.

**Comment by dreamcat4** [comment] 2016-02-03 20:12
Here is the code change i'm testing:

``` sh
#    for proto in inet inet6; do
    for proto in inet; do
```

After clean reboot:

``` sh
$ ifconfig -a
00p0c8154c93a6d Link encap:Ethernet  HWaddr ae:f7:e9:19:a0:3e  
          inet addr:192.168.254.254  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::acf7:e9ff:fe19:a03e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:394 errors:0 dropped:0 overruns:0 frame:0
          TX packets:128 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:59088 (59.0 KB)  TX bytes:14919 (14.9 KB)

docker0   Link encap:Ethernet  HWaddr 02:42:4d:de:01:23  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:4dff:fede:123/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:76 (76.0 B)  TX bytes:90 (90.0 B)

eth0      Link encap:Ethernet  HWaddr 00:1e:ec:d7:3a:1f  
          inet addr:192.168.1.33  Bcast:192.168.255.255  Mask:255.255.0.0
          inet6 addr: fe80::21e:ecff:fed7:3a1f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:208808 errors:0 dropped:0 overruns:0 frame:0
          TX packets:61889 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:254553301 (254.5 MB)  TX bytes:5276986 (5.2 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:354 errors:0 dropped:0 overruns:0 frame:0
          TX packets:354 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:67322 (67.3 KB)  TX bytes:67322 (67.3 KB)

wlan1     Link encap:Ethernet  HWaddr 00:1b:63:09:5f:aa  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         tomato.lan      0.0.0.0         UG    100    0        0 eth0
link-local      *               255.255.0.0     U     1000   0        0 eth0
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
192.168.0.0     *               255.255.0.0     U     0      0        0 00p0c8154c93a6d
192.168.0.0     *               255.255.0.0     U     100    0        0 eth0
irssi.id        *               255.255.255.255 UH    0      0        0 00p0c8154c93a6d
```

After `docker restart pipework`... no new interfaces or routes were added. It might help to go back and try that same steps ^^ without fix. To compare if any positive improvement or its just a null-result where no change from before. But have run out of time today, will have to wait.

**Comment by dreamcat4** [comment] 2016-02-04 11:14
Come back the next day, and there's a load of new interfaces appeared in `ifconfig` output. 16 of them. Like last time one for each container. Yet they are the L2 macvlan bridges created by pipework script. Which are needed / correct. I restart pipework container 2 times, and it re-run jerome's pipework script again on each container. Yet there's no appreciable difference to the interfaces list. No dobling of the interfaces like was seen last time. So must wait a few more days, to come back again and try it again.

Anyway have pushed up a new version of pipework container (v1.1.4) which switches off the IPv6 host bridge creation by default. That is rebuilding on docker hub now. It can't hurt anything if not using IPV6. And there is a new non-default option to switch IPV6 host routes back on.

**Comment by dreamcat4** [comment] 2016-02-04 18:53
Come back this evening, restart pipework container... Still keeps same 16 L2 bridges. No duplicates. So will forget about this for time being. Maybe more time will come back again.

**Comment by dreamcat4** [comment] 2016-02-06 09:55
Switching off just the IPV6 host bridges didn't slow down the host network. Although no duplicate / dead interfaces were created. I have switched off host_routes completely now, so testing that configuration next.

BTW: The end of this section may offer some clue who / how dead interfaces are supposed to be getting cleaned up: https://docs.docker.com/v1.7/articles/networking/#how-docker-networks-a-container

Which in its context refers specificalls to `docker0`. So some more digging would be required / ask jerome if also applies more generally including your OVS bridges.

**Comment by dreamcat4** [comment] 2016-04-11 11:49
Hi.
Going to close this issue now, as 'can't be solved'. With no clear fix in sight.

1st Reason:

Although I was able to see this happen on my own machine, where this bug could be reproduced, unfortunately could not reproduce it again / reliably, to look into further.

It was also determined that switching of `host_routes` feature was a good work-around. To avoid this problem / issues.

2nd Reason:

New versions of Docker (v1.10.x +) [now contains newer networking features](http://stackoverflow.com/questions/35742807/docker-1-10-containers-ip-in-lan), which is better / best for doing external L2 bridge. Further discussions about [best docker-native solutions can now be found on StackOverflow website](http://stackoverflow.com/questions/35742807/docker-1-10-containers-ip-in-lan).

**Closed as completed by dreamcat4** 2016-04-11 11:49 UTC
